---

service:
  listen:
    port: 4128
    ip4:
      - '127.0.0.1'
    ip6:
      - '::1'
    tcp: true
    udp: false  # not yet implemented
    transparent: false

  debug: true
  timeout:
    connection: 5
    handshake: 5
    dial: 5
    intercept: 2

  output:
    fwmark: 0
    interface: ''
    ip4: []
    ip6: []
    multi_ip: 'roundrobin'  # or failover; not yet implemented

vars:
  - name: 'net_private'
    value: ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8']
  - name: 'svc_http'
    value: [80, 443]

rules:
  - match:
      dest: '192.168.100.0/24'
    action: 'drop'

  - match:
      port: ['!443', '!80']
    action: 'drop'

  - match:
      src: '$net_private'
      dest: '$net_private'
      port: '$svc_http'
      protoL4: 'tcp'
    action: 'accept'

  - match:
      dest: '!$net_private'
      port: 443
      protoL4: 'tcp'
    action: 'accept'
  
