---

service:
  listen:
    - mode: 'transparent'
      ip4: ['127.0.0.1']  # is default
      ip6: ['::1']  # is default
      port: 4128
      tcp: true
      udp: false  # not yet implemented
      tproxy: false
    - mode: 'proxyproto'
      port: 4129
    # - mode: 'http'  # not yet implemented
    #   port: 4130
    # - mode: 'https'  # not yet implemented
    #   port: 4131
    # - mode: 'socks5'  # not yet implemented
    #   port: 4132

  certs:
    serverPublic: '/tmp/calamary.crt'
    serverPrivate: '/tmp/calamary.key'
    interceptPublic: '/tmp/calamary.subca.crt'
    interceptPrivate: '/tmp/calamary.subca.key'

  debug: false
  timeout:
    connect: 2000
    process: 1000
    idle: 30000

  output:
    retries: 1  # connect-retries

  metrics:
    enabled: false
    port: 9512

vars:
  - name: 'net_private'
    value: ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8']
  - name: 'svc_http'
    value: [80, 443]

rules:
  - match:
      dest: '192.168.100.0/24'
    action: 'drop'

  - match:
      port: ['!443', '!80']
    action: 'drop'

  - match:
      src: '$net_private'
      dest: '$net_private'
      port: '$svc_http'
      protoL4: 'tcp'
    action: 'accept'

  - match:
      dest: '!$net_private'
      port: [443, 80]
      protoL4: 'tcp'
    action: 'accept'
