---

name: Lint

on:
  push:
    branches: [latest, v*]
    paths:
      - 'lib/**'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [latest, v*]
    paths:
      - 'lib/**'
      - '.github/workflows/lint.yml'

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements_test.txt
        shell: bash

      - name: Running Yamllint
        run: yamllint .
        shell: bash

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          cd lib/main/
          go build
        shell: bash

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: '--config=../.golangci.yml --out-format=colored-line-number'
          working-directory: 'lib'
