---

name: Unit Tests

on:
  push:
    branches: [latest, v*]
    paths:
      - 'lib/**.go'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [latest, v*]
    paths:
      - 'lib/**.go'
      - '.github/workflows/test.yml'

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Running tests
        run: |
          cd lib/
          go test -v ./...
        shell: bash
